name: grain-local

services:
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: obneyai

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,kms
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - PERSISTENCE=0
    volumes:
      - "./localstack-init:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"